# Generated by Django 4.0.1 on 2022-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleCate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateidx', models.IntegerField(unique=True)),
                ('catename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=30, unique=True)),
                ('userpw', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('age', models.DateField()),
                ('gender', models.IntegerField()),
                ('work_state', models.IntegerField()),
                ('middle_level', models.CharField(max_length=30, null=True)),
                ('join_date', models.DateField()),
                ('withdrawal', models.IntegerField(null=True)),
                ('withdrawal_date', models.DateField(null=True)),
            ],
        ),
    ]
