# Generated by Django 4.0.1 on 2022-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='knowcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('large_level', models.CharField(max_length=50)),
                ('top_start_salary', models.IntegerField()),
                ('avg_start_salary', models.IntegerField()),
                ('top_salary', models.IntegerField()),
                ('avg_salary', models.IntegerField()),
                ('avg_age', models.IntegerField()),
                ('man', models.IntegerField()),
                ('woman', models.IntegerField()),
                ('top_work_time', models.IntegerField()),
                ('avg_work_time', models.IntegerField()),
                ('count', models.IntegerField()),
                ('ratio', models.IntegerField()),
            ],
        ),
    ]
